version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: sn_concept
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8001 --settings=config.settings.local
    ports:
      - "8001:8001"
    volumes:
      - .:/sn_concept
    depends_on:
      - db
